CREATE DATABASE IF NOT EXISTS `game`;

USE `game`;

CREATE TABLE IF NOT EXISTS `games` (
    `id` int NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(128) NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    `id_platform` INT NOT NULL,
    `plus` TINYINT(1) NULL, /* Like boolean */
    CONSTRAINT PK_game PRIMARY KEY (id)
) Engine=InnoDB;

CREATE TABLE IF NOT EXISTS `platform` (
    `id` int NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(32) NOT NULL,
    CONSTRAINT PK_platform PRIMARY KEY (id)
) Engine=InnoDB;

ALTER TABLE `games` ADD FOREIGN KEY FK_id_platform(`id_platform`)
    REFERENCES `platform` (`id`);

INSERT INTO `platform` (name)
    VALUES  ('XBOX 360'),
            ('XBOX One'),
            ('PC'),
            ('PS1'),
            ('PS2'),
            ('PS3'),
            ('PS4'),
            ('PS5'),
            ('Nintendo Switch');

/* Xbox 360 Games */

INSERT INTO `games` (`name`, `description`, `id_platform`, `plus`)
VALUES  ("Army of two 40 day","", 1, 0),
        ("Assassins creed ","", 1, 0),
        ("Assassins creed II","", 1, 0),
        ("Assassins creed La hermandad","", 1, 0),
        ("Assassins creed Revelations","", 1, 0),
        ("Assassins creed III","", 1, 0),
        ("Bionic commando","", 1, 0),
        ("Call of duty 3","", 1, 0),
        ("Call of duty World at war","", 1, 0),
        ("Crackdown","", 1, 0),
        ("Dead island","", 1, 0),
        ("Dead rising","", 1, 0),
        ("Dead rising 2 off the record","", 1, 0),
        ("Dragon ball ragin blast","", 1, 0),
        ("El padrino II","", 1, 0),
        ("El señor de los anillos la conquista","", 1, 0),
        ("Fable aniversary","", 1, 0),
        ("Fable II","", 1, 0),
        ("Fable III","", 1, 0),
        ("Fallout new vegas","", 1, 0),
        ("Far cry 2","", 1, 0),
        ("Final fantasy XIII-2 (solo disk 3)","", 1, 0),
        ("Frontlines fuel of war","", 1, 0),
        ("Gears of war(eu e esteban)","", 1, 0),
        ("Gears of war 2","", 1, 0),
        ("Gears of war 3","", 1, 0),
        ("Grand theft auto IV","", 1, 0),
        ("Halo 3","", 1, 0),
        ("Halo reach","", 1, 0),
        ("Iron man","", 1, 0),
        ("Left 4 dead 2","", 1, 0),
        ("Medal of Honor","", 1, 0),
        ("Overlord","", 1, 0),
        ("Perfect dark zero","", 1, 0),
        ("Phantasy start universe","", 1, 0),
        ("Prince of Persia","", 1, 0),
        ("Prey","", 1, 0),
        ("Red faction armageddon","", 1, 0),
        ("SmackDown vs Raw 2008","", 1, 0),
        ("Saints row","", 1, 0),
        ("Saints row 2","", 1, 0),
        ("Saints row the third","", 1, 0),
        ("Sega superstars tennis","", 1, 0),
        ("Tekken 6","", 1, 0),
        ("Time shift","", 1, 0),
        ("Tom Clancys Ghost recon advanced warfighter 2","", 1, 0),
        ("Tom Clamcys Rainbow Six Vegas 2","", 1, 0),
        ("Too human","", 1, 0),
        ("Transformers","", 1, 0),
        ("Viking: Battle for Asgard","", 1, 0),
        ("Warhammer Battle march","", 1, 0),
        ("Wolfenstein","", 1, 0),
        ("WWE Legends of WestleMania","", 1, 0);


/* Xbox One Games */

INSERT INTO `games` (`name`, `description`, `id_platform`, `plus`)
    VALUES ("RARE PLAY", "", 2, 0);


/* PS3 Games */

INSERT INTO `games` (`name`, `description`, `id_platform`, `plus`)
    VALUES  ("Assassins creed Heritage edition", "", 6, 0),
            ("Assassins creed IV Black Flag", "", 6, 0),
            ("Assassins creed Rogue", "", 6, 0),
            ("Battlefield:Bad Company 2", "", 6, 0),
            ("Battlefield 3 (Repetido)", "", 6, 0),
            ("Bayonetta", "", 6, 0),
            ("Bioshock", "", 6, 0),
            ("Bioshock infinite", "", 6, 0),
            ("Bleach soul resurreccion", "", 6, 0),
            ("Borderlands", "", 6, 0),
            ("Brother in arms Hell's Highway", "", 6, 0),
            ("Call of duty Black ops", "", 6, 0),
            ("Call of duty Black ops II", "", 6, 0),
            ("Call of duty Ghost", "", 6, 0),
            ("Call of duty modern warfare 2", "", 6, 0),
            ("Call of duty modern warfare 3", "", 6, 0),
            ("Call of Juarez: Bound in Blood", "", 6, 0),
            ("Castlevania Lords of shadow", "", 6, 0),
            ("Condemned 2", "", 6, 0),
            ("Crysis 2 limited edition", "", 6, 0),
            ("Dante's Inferno", "", 6, 0),
            ("Demon's Souls", "", 6, 0),
            ("Dark souls Prepare to die edition", "", 6, 0),
            ("Dark souls 2 Black armour edition", "", 6, 0),
            ("Darksiders", "", 6, 0),
            ("Darksiders 2 (Rober)", "", 6, 0),
            ("Dead island Double pack", "", 6, 0),
            ("Dead space", "", 6, 0),
            ("Dead space 2 Limited edition", "", 6, 0),
            ("Destroy all humans!Path of the Furon", "", 6, 0),
            ("Deus Ex Human revolution", "", 6, 0),
            ("Devil may cry 4 Steelbook", "", 6, 0),
            ("Diablo 3", "", 6, 0),
            ("Dragon age 2", "", 6, 0),
            ("Dragon age inquisition", "", 6, 0),
            ("Dragon ball z Budokai HD Collection", "", 6, 0),
            ("Dragon ball Z Ultimate tenkaichi", "", 6, 0),
            ("Dragon ball raging blast 2", "", 6, 0),
            ("Dragon ball Xenoverse", "", 6, 0),
            ("Dragons Dogma dark ariser", "", 6, 0),
            ("Duke nukem forever", "", 6, 0),
            ("Fallout 3", "", 6, 0),
            ("Fallout new vegas(UK)(ESP)", "", 6, 0),
            ("Far cry 3", "", 6, 0),
            ("Far cry 4", "", 6, 0),
            ("F.E.A.R 2", "", 6, 0),
            ("Fifa 12", "", 6, 0),
            ("Fifa 13", "", 6, 0),
            ("Fifa 15", "", 6, 0),
            ("Final fantasy XIII-2", "", 6, 0),
            ("God of war collection", "", 6, 0),
            ("God of war collection volumen II", "", 6, 0),
            ("God of war III", "", 6, 0),
            ("God of war Ascension", "", 6, 0),
            ("Grand theft auto V", "", 6, 0),
            ("Heavenly sword", "", 6, 0),
            ("Hora de aventuras Finn y Jake inverstigadores", "", 6, 0),
            ("Hunted demons forge", "", 6, 0),
            ("Infamous", "", 6, 0),
            ("Infamous 2", "", 6, 0),
            ("Invizimals:El reino escondido", "", 6, 0),
            ("Ironman 2", "", 6, 0),
            ("Jak & Daxter Triology", "", 6, 0),
            ("Just Cause 2", "", 6, 0),
            ("Kane & Lynch: Dead men", "", 6, 0),
            ("Kane & Lynch 2: Dogs days edicion limitada", "", 6, 0),
            ("Killzone 2", "", 6, 0),
            ("Killzone 3", "", 6, 0),
            ("Kingdom Hearts HD 1.5 ReMIX (ILG)", "", 6, 0),
            ("LittleBigPlanet 2", "", 6, 0),
            ("Lost planet 2", "", 6, 0),
            ("Los Simpson El videojuego", "", 6, 0),
            ("Mafia II steelbook", "", 6, 0),
            ("Majin and the forsaken kingdom", "", 6, 0),
            ("Mass effect 3", "", 6, 0),
            ("Metal Gear Solid 4", "", 6, 0),
            ("Metal Gear Rising revengeance", "", 6, 0),
            ("Metro last light", "", 6, 0),
            ("Modnation racers", "", 6, 0),
            ("Mortal Kombat", "", 6, 0),
            (" Naruto Shippuden Ultimate ninja storm 3 (ILG)", "", 6, 0),
            ("Need for speed the run", "", 6, 0),
            ("Ninja gaiden sigma", "", 6, 0),
            ("Ninja gaiden sigma 2", "", 6, 0),
            ("Ninja gaiden z Yaiba", "", 6, 0),
            ("Ni no kuni la ira de la bruja blanca", "", 6, 0),
            ("One piece: Pirate warriors", "", 6, 0),
            ("Operation flashpoint red river", "", 6, 0),
            ("Overlord rasing hell", "", 6, 0),
            ("Overlord II", "", 6, 0),
            ("Playstation all-stars battle royale", "", 6, 0),
            ("Prince of Persia triologia", "", 6, 0),
            ("Prince of Persia Las arenas olvidadas", "", 6, 0),
            ("Prince of Persia", "", 6, 0),
            ("Pro Evolution Soccer 2014", "", 6, 0),
            ("Prototype 2", "", 6, 0),
            ("Rage Anarchy edition", "", 6, 0),
            ("Ratchet and clank triology", "", 6, 0),
            ("Ratchet & Clanck: Armados hasta los dientes", "", 6, 0),
            ("Ratchet & Clanck: Atrapados en el tiempo", "", 6, 0),
            ("Ratchet & Clanck: En busca del tesoro","", 6, 0),
            ("Ratchet & Clanck: Nexus","", 6, 0),
            ("Ratchet & Clanck: Q-Force(Digital)","", 6, 0),
            ("Ratchet & Clanck: Todos para uno(Digital ILG)","", 6, 0),
            ("Rayman origins+legends","", 6, 0),
            ("Resident evil 5","", 6, 0),
            ("Resident evil 6","", 6, 0),
            ("Resistence 2","", 6, 0),
            ("Sacred 2","", 6, 0),
            ("Sacred 3","", 6, 0),
            ("Skylanders spyro adventure","", 6, 0),
            ("Skylanders Giants","", 6, 0),
            ("Smackdown vs raw 2010","", 6, 0),
            ("Sniper Ghost Warrior","", 6, 0),
            ("Sniper Ghost Warrior 2 Limited edition","", 6, 0),
            ("Sonic Generations","", 6, 0),
            ("Sonic & sega all-stars racing","", 6, 0),
            ("SoulCalivur V(Fighting Edition)","", 6, 0),
            ("Spec ops the line","", 6, 0),
            ("Super street fighter IV arcade edition","", 6, 0),
            ("Sleeping dogs","", 6, 0),
            ("Tales of Symphonia chronicles/Tales of Graces f","", 6, 0),
            ("Tekken 6(Fighting Edition)","", 6, 0),
            ("Tekken tag tournament 2(Fighting Edition)","", 6, 0),
            ("The amazing spider-man","", 6, 0),
            ("The amazing spider-man 2","", 6, 0),
            ("The elder scrolls IV Oblivion GOTY","", 6, 0),
            ("The elder scrolls V Skyrim legendary edition","", 6, 0),
            ("The walking dead survival instinct","", 6, 0),
            ("Tomb raider triology","", 6, 0),
            ("Tomb raider","", 6, 0),
            ("Tom clancys Ghost recon advanced warfighter 2","", 6, 0),
            ("Tom clancys Rainbow six vegas","", 6, 0),
            ("Tom clancys Splinter cell triology","", 6, 0),
            ("Tom clancys Splinter cell Blacklist","", 6, 0),
            ("TNA Impact! Total nonstop action wrestling","", 6, 0),
            ("Two worlds II GOTY","", 6, 0),
            ("UFC 2009 Undisputed","", 6, 0),
            ("Up","", 6, 0),
            ("Vanquish","", 6, 0),
            ("Watch dogs","", 6, 0);


/* PS4 Games  */

INSERT INTO `games` (`name`, `description`, `id_platform`, `plus`)
    VALUES  ("A.O.T ", "", 7, 0),
            ("Accel World vs Sword art Online", "", 7, 0),
            ("Amnesia: Collection(Digital)", "", 7, 0),
            ("Ancestors Legacy", "", 7, 0),
            ("Arizona Sunshine VR(Digital)", "", 7, 0),
            ("Army Triology (Digital)", "", 7, 0),
            ("Assassins creed The Ezio collection(Rober)", "", 7, 0),
            ("Assassins creed 3 Remastered(digital)", "", 7, 0),
            ("Assassins creed liberation remastered(digital)", "", 7, 0),
            ("Assassins creed IV Black Flag(Rober)", "", 7, 0),
            ("Assassins creed unity", "", 7, 0),
            ("Assassins creed syndicate", "", 7, 0),
            ("Assassins creed origins+ seasson pass", "", 7, 0),
            ("Assassins creed Odyssey + Season pass", "", 7, 0),
            ("Assassins creed Valhalla(Rober)", "", 7, 0),
            ("Astro bot (digital)", "", 7, 0),
            ("Batman Arkham collection", "", 7, 0),
            ("Battlefield 4", "", 7, 0),
            ("Battlefield 1", "", 7, 0),
            ("Berserk and the Band oh the Hawk", "", 7, 0),
            ("Black clover quartet knights", "", 7, 0),
            ("Blasphemous (Digital)", "", 7, 0),
            ("Bloodborne GOTY", "", 7, 0),
            ("Borderlands: The handsome collection", "", 7, 0),
            ("Borderlands 3 Delux Edition", "", 7, 0),
            ("Bullstorm Full Clip Edition", "", 7, 0),
            ("Call of duty 4 Moder Warfare(Digital)", "", 7, 0),
            ("Call of duty black ops III (Zombie Chronicles)", "", 7, 0),
            (" Call of duty black ops IIII", "", 7, 0),
            ("Call of duty advance warfare", "", 7, 0),
            ("Call of duty infinity warfare", "", 7, 0),
            ("Call of duty Cold War(Digital)", "", 7, 0),
            ("Days gone solo steelbok", "", 7, 0),
            ("De blob 2", "", 7, 0),
            ("Dead island Double pack(Digital)", "", 7, 0),
            ("Dead rising 4:Franks big package", "", 7, 0),
            ("Dead stranding", "", 7, 0),
            ("Destroy all humans! Remake", "", 7, 0),
            ("Destroy all humans! 2 (Digital)", "", 7, 0),
            ("Deus Ex Mankind divided", "", 7, 0),
            ("Devil may cry hd collection", "", 7, 0),
            ("Diablo III Ethernal collection", "", 7, 0),
            ("Digimon World next order", "", 7, 0),
            ("Dishonored Definitive Edition", "", 7, 0),
            ("Dishonored 2", "", 7, 0),
            ("DOOM VR", "", 7, 0),
            ("DOOM Eternal Deluxe Edition", "", 7, 0),
            ("Dragon Ball Xenovers 1+2", "", 7, 0),
            ("Dragon Ball Fighterz(+SEASSON PASS 1)(Digital)", "", 7, 0),
            ("Dragon Quest XI:Ecos de un pasado perdido", "", 7, 0),
            ("Cup Head(Digital)", "", 7, 0),
            ("Dying light aniversary edition", "", 7, 0),
            ("ELEX", "", 7, 0),
            ("Everybody's Golf VR (digital)", "", 7, 0),
            ("Fade to silence", "", 7, 0),
            ("Fallout 4 GOTY", "", 7, 0),
            ("Farmers Dinasty", "", 7, 0),
            ("Far cry 3 Classic edition(Digital)", "", 7, 0),
            ("Far cry 5(+season pass)", "", 7, 0),
            ("Fifa 16", "", 7, 0),
            ("Fifa 17", "", 7, 0),
            ("Fifa 18(Rober)", "", 7, 0),
            ("Final fantasy x | x-ii", "", 7, 0),
            ("Final fantasy Type 0 HD", "", 7, 0),
            ("Final fantasy xv royal edition", "", 7, 0),
            ("Final Fantasy VII Remake", "", 7, 0),
            ("Ghost Recon Wildlands", "", 7, 0),
            ("Ghost Recon BreakPoint", "", 7, 0),
            ("God eater Resurrection(Digital)", "", 7, 0),
            ("God eater 2 Rage Burst(Digital)", "", 7, 0),
            ("God of war 3 Remastered", "", 7, 0),
            ("God of war(Rober regalo)", "", 7, 0),
            ("GTA V", "", 7, 0),
            ("Hellblade senua's sacrifice", "", 7, 0),
            ("Hero Defense", "", 7, 0),
            ("Hollow Knight", "", 7, 0),
            ("Horizon zero dawn complete edition(Rober)", "", 7, 0),
            ("Homefront: The Revolution", "", 7, 0),
            ("Immortal Fenix Rising GOLD", "", 7, 0),
            ("Injustice Gods Among us Ultimate Edition(Digital)", "", 7, 0),
            ("Infamous second son", "", 7, 0),
            ("Infamous first light", "", 7, 0),
            ("Inside/Limbo", "", 7, 0),
            ("Intruders hide and seek VR", "", 7, 0),
            ("J-Stars vs +", "", 7, 0),
            ("Journey(Digital)", "", 7, 0),
            ("Just Cause 4 Gold Edition+Steelbok", "", 7, 0),
            ("Just Cause 4 Gold Edition+Stelbok", "", 7, 0),
            ("Killing floor Double Feature", "", 7, 0),
            ("Killzone: Shadow fall", "", 7, 0),
            ("Kingdom hearts 1.5 y 2.5", "", 7, 0),
            ("Kingdom hearts 2.8(Rober)", "", 7, 0),
            ("Kingdom hearts 3(Rober)", "", 7, 0),
            ("La LEGO NINJAGO Película El videojuego(Digital)", "", 7, 0),
            ("Lords of the Fallen Complete Edition", "", 7, 0),
            ("Mad max", "", 7, 0),
            ("Mass effect Andromeda", "", 7, 0),
            ("Metal gear V: Definitive Experience", "", 7, 0),
            ("Metro Exodus", "", 7, 0),
            ("Minecraft", "", 7, 0),
            ("Monster hunter World(Digital)", "", 7, 0),
            ("Mortal Kombat XL", "", 7, 0),
            ("Mortal Kombat 11", "", 7, 0),
            ("My hero one justice", "", 7, 0),
            ("Naruto Shippuden ninja storm 4 road to boruto", "", 7, 0),
            ("Need for speed(Digital)", "", 7, 0),
            ("NieR:automata game of the yorha", "", 7, 0),
            ("Nioh", "", 7, 0),
            ("Ni no kuni 2 ", "", 7, 0),
            ("No man's sky", "", 7, 0),
            ("Okami hd", "", 7, 0),
            ("One piece burning blood", "", 7, 0),
            ("One piece Unlimited world red delux", "", 7, 0),
            ("One piece World Sheeker", "", 7, 0),
            ("One punch man", "", 7, 0),
            ("Outlast Trinity", "", 7, 0),
            ("Overcooked (Digital)", "", 7, 0),
            ("Overcooked 2+seasson pass(Digital)", "", 7, 0),
            ("Persona 5 royal launch edition", "", 7, 0),
            ("PlayStation Worlds VR (digital)", "", 7, 0),
            ("Plants vs zombies garden warfare", "", 7, 0),
            ("Plants vs zombies garden warfare 2 (Digital)", "", 7, 0),
            ("Portal Knights", "", 7, 0),
            ("Ratchet and clank(Rober)", "", 7, 0),
            ("Red dead redemption 2", "", 7, 0),
            ("Red Faction Guerrilla Re-Mas-te-red", "", 7, 0),
            ("Resident evil origins collection", "", 7, 0),
            ("Resident evil 4", "", 7, 0),
            ("Resident evil 7 VR (digital)", "", 7, 0),
            ("Resident evil Revelations HD", "", 7, 0),
            ("Resident evil Revelations 2 Box", "", 7, 0),
            ("Rigs Mechanized Combat league VR", "", 7, 0),
            ("Shadow of the Colossus", "", 7, 0),
            ("Sherlock Holmes:The Devil's Daughter (Digital)", "", 7, 0),
            ("Sniper elite 4 delux edition(Digital)", "", 7, 0),
            ("Sniper elite V2 Remastered(Digital)", "", 7, 0),
            ("Sombras de mordor GOTY", "", 7, 0),
            ("Sombras de guerra GOTY", "", 7, 0),
            ("Soul Calibur VI", "", 7, 0),
            ("South Park La vara de la verdad (digital)", "", 7, 0),
            ("South Park Retaguardia en peligro", "", 7, 0),
            ("Spider-man", "", 7, 0),
            ("Stardew valley collectors edition", "", 7, 0),
            ("Starlink battle for atlas", "", 7, 0),
            ("Star Wars Battlefront + Season pass(Digital)", "", 7, 0),
            ("Star Wars Jedi: Fallen Order", "", 7, 0),
            ("Street Fighter 30th aniversary collection", "", 7, 0),
            ("Sword art online Fatal Bullet", "", 7, 0),
            ("Sword art online Hollow realization", "", 7, 0),
            ("The division 2 Washington Edition", "", 7, 0),
            ("The elder scrolls V Skyrim VR (digital)", "", 7, 0),
            ("The evil within(Rober)", "", 7, 0),
            ("The last guardian steelbook", "", 7, 0),
            ("The last of us Remasterizado", "", 7, 0),
            ("The last of us parte 2 Collectors", "", 7, 0),
            ("The Outer Worlds", "", 7, 0),
            ("The surge", "", 7, 0),
            ("The witcher 3 wild hunt GOTY", "", 7, 0),
            ("Thief", "", 7, 0),
            ("Titanfall 2 Ultimate edition (Digital)", "", 7, 0),
            ("Tokyo Ghoul: re Call to Exist", "", 7, 0),
            ("Tomb raider: Definitive edition(Digital)", "", 7, 0),
            ("Rise of The Tomb raider(20 Aniversario )", "", 7, 0),
            ("Tom clancys rainbow six siege", "", 7, 0),
            ("Trial fusion awesome max edition", "", 7, 0),
            ("Tropico 6 Prez edition", "", 7, 0),
            ("UFC 2", "", 7, 0),
            ("Ultimate VR Collection", "", 7, 0),
            ("Uncharted the Nathan Drake collection", "", 7, 0),
            ("Uncharted 4 El desenlace del ladrón", "", 7, 0),
            ("Uncharted el legado perdido", "", 7, 0),
            ("Unravel(Digital)", "", 7, 0),
            ("Unravel 1+2 (Digital)", "", 7, 0),
            ("Watch Dogs Complete Edition (Rober)", "", 7, 0),
            ("Watch Dogs 2", "", 7, 0),
            ("Wolfestein The new order", "", 7, 0),
            ("WWE 2K18", "", 7, 0),
            ("XCOM 2", "", 7, 0),
            ("Yakuza like a dragon ", "", 7, 0),
            ("Zombie Driver: Inmortal Edition(Digital)", "", 7, 0);


/* PS4 Games + Plus */

INSERT INTO `games` (`name`, `description`, `id_platform`, `plus`)
    VALUES  ("Aces of the multiverse", "", 7, 0),
            ("Bioshock:The Collection", "", 7, 0),
            ("Call of Duty WWII", "", 7, 0),
            ("Call of duty Modern Warfare 2 Remastered", "", 7, 0),
            ("Citie Skylines", "", 7, 0),
            ("Dirt 2.0", "", 7, 0),
            ("Down of fear", "", 7, 0),
            ("Erica", "", 7, 0),
            ("Fall Guys: Ultimate Knockout", "", 7, 0),
            ("Farming simulador 19", "", 7, 0),
            ("Firewall Zero Hour", "", 7, 0),
            ("Greed Fall", "", 7, 0),
            ("Holfraine", "", 7, 0),
            ("Hollow Knight", "", 7, 0),
            ("Just Cause 4", "", 7, 0),
            ("Los sims 4", "", 7, 0),
            ("Massira", "", 7, 0),
            ("NBA2k20", "", 7, 0),
            ("Need for speed payback", "", 7, 0),
            ("Nubla 2", "", 7, 0),
            ("Playerunknown´s Battlegrounds", "", 7, 0),
            ("Shadow of the Colossus", "", 7, 0),
            ("Sombras de guerra", "", 7, 0),
            ("Sonic Forces", "", 7, 0),
            ("Star Wars Battlefront 2", "", 7, 0),
            ("Street Fighter V", "", 7, 0),
            ("Rise of Tomb Raider(20 Aniversario )", "", 7, 0),
            ("Shadow of the Tomb raider ", "", 7, 0),
            ("Rocket Arena", "", 7, 0),
            ("Traesure Rangers", "", 7, 0),
            ("Uncharted 4", "", 7, 0),
            ("Vampyr", "", 7, 0),
            ("Worms Rumble", "", 7, 0);


/* PS5 Games */

INSERT INTO `games` (`name`, `description`, `id_platform`, `plus`)
    VALUES  ("Bugsnax", "", 8, 0),
            ("Maneater", "", 8, 0);

/* Xbox One Games */

INSERT INTO `games` (`name`, `description`, `id_platform`, `plus`)
    VALUES  ("Pokemon Espada Steelbook", "", 9, 0),
            ("Super Mario 3D All stars", "", 9, 0),
            ("Super smash bros ultimate", "", 9, 0);


/* QUERIES */

/*
Game name and platform name where platform = PS5:

SELECT games.name, platform.name 
FROM games INNER JOIN platform 
ON games.id_platform = platform.id 
WHERE platform.name = 'PS5';

*/